boundary_conditions:
  p_stagnation:  10e5
  T_stagnation: 500
  critical_flow: True # If True the PIF will be performed
  mach_inlet: None
  mass_flow_inlet: None

# Numerical settings
numerical_settings:
  Nx: 600 # Number of cells
  
 
nozzle_parameters:
  type: planar # Planar or ciircular (still to be implemented)
  r0: 3
  rt: 0.5
  roughness: 0.000002
 
fluid:
  perfect_gas: false
  fluid_name: CO2
 
