boundary_conditions:
  p_stagnation:  61e5
  T_stagnation: 293.15
  critical_flow: True # If True the PIF will be performed
  mach_inlet: None
  mass_flow_inlet: 52.106

nozzle_parameters:
  radius_in: 5e-3
  radius_throat: 0.12e-3
  radius_out: 0.27e-3
  convergent_length: 27.35e-3
  divergent_length: 56.15e-3
  roughness: 0
  type: Planar # Planar or Axisymmetric or Convergent
  width: 3e-3  # Only for planar nozzles
 
fluid:
  perfect_gas: false
  fluid_name: CO2

# boundary_conditions:
#   p_stagnation:  84.74e5
#   T_stagnation: 313
#   critical_flow: True # If True the PIF will be performed
#   mach_inlet: None
#   mass_flow_inlet: 52.106

# nozzle_parameters:
#   type: Axisymmetric # Planar or Axisymmetric or Convergent
#   radius_in: 0.5
#   radius_throat: 0.3
#   radius_out: 0.4
#   convergent_length: 0.5
#   divergent_length: 0.5
#   roughness: 1e-6
 
# fluid:
#   perfect_gas: false
#   fluid_name: CO2
 
